#!/usr/bin/expect -f

set timeout 30
set host "72.60.10.222"
set user "root"
set password "Master230514@"

spawn ssh $user@$host

expect {
    "yes/no" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}

expect "#"

# Fazer backup
send "cd /var/www/tubemine\r"
expect "#"
send "cp src/app/api/admin/users/route.ts src/app/api/admin/users/route.ts.backup\r"
expect "#"

# Aplicar correção
send "cat > src/app/api/admin/users/route.ts << 'EOF'\r"
expect "#"

send "import { NextRequest, NextResponse } from 'next/server'\r"
send "import { getDatabase } from '@/lib/database'\r"
send "\r"
send "export async function GET(request: NextRequest) {\r"
send "  try {\r"
send "    // Verificar autenticação\r"
send "    const authHeader = request.headers.get('authorization')\r"
send "    if (!authHeader || !authHeader.startsWith('Bearer ')) {\r"
send "      return NextResponse.json(\r"
send "        { error: 'Token de autenticação necessário' },\r"
send "        { status: 401 }\r"
send "      )\r"
send "    }\r"
send "\r"
send "    const token = authHeader.substring(7)\r"
send "    const db = await getDatabase()\r"
send "    \r"
send "    // Verificar token e obter usuário\r"
send "    const session = await db.get(\r"
send "      'SELECT user_id FROM user_sessions WHERE token = ?',\r"
send "      [token]\r"
send "    )\r"
send "\r"
send "    if (!session) {\r"
send "      return NextResponse.json(\r"
send "        { error: 'Token inválido' },\r"
send "        { status: 401 }\r"
send "      )\r"
send "    }\r"
send "\r"
send "    const userId = session.user_id\r"
send "\r"
send "    // Verificar se é admin\r"
send "    const user = await db.get(\r"
send "      'SELECT role FROM users WHERE id = ?',\r"
send "      [userId]\r"
send "    )\r"
send "\r"
send "    if (user?.role !== 'admin') {\r"
send "      return NextResponse.json(\r"
send "        { error: 'Acesso negado. Apenas administradores.' },\r"
send "        { status: 403 }\r"
send "      )\r"
send "    }\r"
send "\r"
send "    // Buscar todos os usuários\r"
send "    const users = await db.all(\`\r"
send "      SELECT\r"
send "        u.id,\r"
send "        u.name,\r"
send "        u.email,\r"
send "        u.role,\r"
send "        u.created_at,\r"
send "        u.updated_at,\r"
send "        COUNT(sl.id) as search_count\r"
send "      FROM users u\r"
send "      LEFT JOIN search_logs sl ON u.id = sl.user_id\r"
send "      GROUP BY u.id\r"
send "      ORDER BY u.created_at DESC\r"
send "    \`)\r"
send "\r"
send "    // Buscar assinaturas mais recentes para cada usuário\r"
send "    const subscriptions = await db.all(\`\r"
send "      SELECT \r"
send "        s1.user_id,\r"
send "        s1.plan_type,\r"
send "        s1.status,\r"
send "        s1.valid_until\r"
send "      FROM subscriptions s1\r"
send "      LEFT JOIN subscriptions s2 ON s1.user_id = s2.user_id AND s1.created_at < s2.created_at\r"
send "      WHERE s2.user_id IS NULL\r"
send "    \`)\r"
send "\r"
send "    // Criar mapa de assinaturas\r"
send "    const subscriptionMap = new Map()\r"
send "    subscriptions.forEach((sub: any) => {\r"
send "      subscriptionMap.set(sub.user_id, {\r"
send "        plan_type: sub.plan_type,\r"
send "        status: sub.status,\r"
send "        valid_until: sub.valid_until\r"
send "      })\r"
send "    })\r"
send "\r"
send "    // Formatar dados\r"
send "    const formattedUsers = users.map((user: any) => {\r"
send "      const subscription = subscriptionMap.get(user.id) || {\r"
send "        plan_type: 'free',\r"
send "        status: 'active',\r"
send "        valid_until: null\r"
send "      }\r"
send "      \r"
send "      return {\r"
send "        id: user.id,\r"
send "        name: user.name,\r"
send "        email: user.email,\r"
send "        role: user.role,\r"
send "        created_at: user.created_at,\r"
send "        updated_at: user.updated_at,\r"
send "        subscription,\r"
send "        search_count: user.search_count || 0\r"
send "      }\r"
send "    })\r"
send "\r"
send "    return NextResponse.json({ users: formattedUsers })\r"
send "\r"
send "  } catch (error) {\r"
send "    console.error('Erro ao buscar usuários:', error)\r"
send "    return NextResponse.json(\r"
send "      { error: 'Erro interno do servidor' },\r"
send "      { status: 500 }\r"
send "    )\r"
send "  }\r"
send "}\r"
send "EOF\r"
expect "#"

# Reiniciar aplicação
send "pm2 restart tubemine-saas\r"
expect "#"

# Aguardar
send "sleep 5\r"
expect "#"

# Testar
send "curl -X POST http://localhost:3000/api/auth/login -H 'Content-Type: application/json' -d '{\"email\":\"admin@tubemine.com\",\"password\":\"b50x20Hi@\"}' | grep -o '\"token\":\"[^\"]*\"' | cut -d'\"' -f4\r"
expect "#"

send "echo 'Correção aplicada com sucesso!'\r"
expect "#"

send "exit\r"
expect eof
